### ISSUE TITLE
The code doesn't run.

### ISSUE THREAD

**Issue by jackmufasa** [Breens-Mbaka/MpesaUiCloneAndroid#2]
The code seems not to be running when integrated with android studio. Kindly help

**Comment by Breens-Mbaka** [comment]
I've update gradle dependecies try updating the branch and running again @jackmufasa

**Comment by jackmufasa** [comment]
Ok let me check it out. You can check out your emails, I communicated to you via them.

**Comment by Breens-Mbaka** [comment]
Was this fixed @jackmufasa ?

**Comment by Breens-Mbaka** [comment]
Closing this issue if you have any issues just copy the XML layout form GitHub and play around with it
